version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: web3certs-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: web3certs
    ports:
      - "5433:5432" # هتوصل من خلال localhost:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: web3certs-cache
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
