packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - keccak
  - msgpackr-extract
  - prisma
  - secp256k1
  - sharp
  - unrs-resolver
